import React, { useState } from 'react';
import { CreateRoomRequest, RoomSettings } from '../../../../shared/src/types';

interface Props {
  playerName: string;
  onClose: () => void;
  onRoomCreated: (roomData: any) => void;
}

const CreateRoomModal: React.FC<Props> = ({ playerName, onClose, onRoomCreated }) => {
  const [roomName, setRoomName] = useState('');
  const [isPublic, setIsPublic] = useState(true);
  const [maxPlayers, setMaxPlayers] = useState(10);
  const [autoValidateClaims, setAutoValidateClaims] = useState(true);
  const [creating, setCreating] = useState(false);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();

    if (!roomName.trim()) {
      alert('Please enter a room name');
      return;
    }

    const settings: RoomSettings = {
      maxPlayers,
      isPublic,
      autoValidateClaims
    };

    const requestData: CreateRoomRequest = {
      roomName: roomName.trim(),
      playerName: playerName.trim(),
      settings
    };

    try {
      setCreating(true);

      // In a real implementation, this would connect to socket and emit create-room event
      // For now, we'll simulate the creation
      console.log('Creating room:', requestData);

      // Simulate API call delay
      await new Promise(resolve => setTimeout(resolve, 1000));

      // Simulate successful room creation
      const mockRoomData = {
        room: {
          id: 'ABC123', // This would be generated by backend
          name: roomName,
          hostId: 'host-id',
          players: [],
          maxPlayers,
          status: 'waiting',
          currentNumber: null,
          calledNumbers: [],
          winningClaims: [],
          isPublic,
          createdAt: new Date()
        },
        player: {
          id: 'player-id',
          name: playerName,
          roomId: 'ABC123',
          tickets: [],
          isHost: true,
          joinedAt: new Date(),
          isConnected: true
        }
      };

      onRoomCreated(mockRoomData);

    } catch (error) {
      console.error('Error creating room:', error);
      alert('Failed to create room. Please try again.');
    } finally {
      setCreating(false);
    }
  };

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <button className="modal-close" onClick={onClose}>
          ×
        </button>

        <h2 className="text-2xl font-bold mb-6">Create New Room</h2>

        <form onSubmit={handleSubmit}>
          <div className="form-group">
            <label className="form-label">Room Name</label>
            <input
              type="text"
              value={roomName}
              onChange={(e) => setRoomName(e.target.value)}
              className="form-input"
              placeholder="Enter room name"
              maxLength={30}
              required
            />
            <small className="text-muted">Max 30 characters</small>
          </div>

          <div className="form-group">
            <label className="form-label">Room Type</label>
            <div className="flex gap-4">
              <label className="flex-center gap-2">
                <input
                  type="radio"
                  name="roomType"
                  checked={isPublic}
                  onChange={() => setIsPublic(true)}
                />
                <span>Public (appears in room list)</span>
              </label>
              <label className="flex-center gap-2">
                <input
                  type="radio"
                  name="roomType"
                  checked={!isPublic}
                  onChange={() => setIsPublic(false)}
                />
                <span>Private (join by code only)</span>
              </label>
            </div>
          </div>

          <div className="form-group">
            <label className="form-label">Max Players</label>
            <select
              value={maxPlayers}
              onChange={(e) => setMaxPlayers(Number(e.target.value))}
              className="form-select"
            >
              <option value={6}>6 Players</option>
              <option value={7}>7 Players</option>
              <option value={8}>8 Players</option>
              <option value={9}>9 Players</option>
              <option value={10}>10 Players</option>
            </select>
          </div>

          <div className="form-group">
            <label className="flex-center gap-2">
              <input
                type="checkbox"
                checked={autoValidateClaims}
                onChange={(e) => setAutoValidateClaims(e.target.checked)}
              />
              <span>Auto-validate claims</span>
            </label>
            <small className="text-muted">
              Automatically validate player claims when made
            </small>
          </div>

          <div className="flex gap-4 mt-6">
            <button
              type="button"
              onClick={onClose}
              className="btn btn-secondary flex-1"
              disabled={creating}
            >
              Cancel
            </button>
            <button
              type="submit"
              className="btn flex-1"
              disabled={creating || !roomName.trim()}
            >
              {creating ? 'Creating...' : 'Create Room'}
            </button>
          </div>
        </form>

        <div className="mt-6 p-4 bg-gray-50 rounded-lg">
          <h4 className="font-semibold mb-2">Room Settings Info:</h4>
          <ul className="text-sm text-muted space-y-1">
            <li>• You will be the host and can start the game</li>
            <li>• Room code will be generated automatically</li>
            <li>• Each player can select up to 3 tickets</li>
            <li>• Game requires minimum 2 players to start</li>
          </ul>
        </div>
      </div>
    </div>
  );
};

export default CreateRoomModal;